global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'todo_app'
    static_configs:
      - targets: ['todo-app:5000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']